/*
 * ICU common data table of contents for icudt57l.dat
 * Automatically generated by icu/source/tools/gencmn/gencmn .
 */

#include "unicode/utypes.h"
#include "unicode/udata.h"

/* external symbol declarations for data (8 files) */
extern const char
    icudt57l_cnvalias_icu[],
    icudt57l_confusables_cfu[],
    icudt57l_ibm_943_P15A_2003_cnv[],
    icudt57l_ibm_949_P110_1999_cnv[],
    icudt57l_ibm_949_P11A_1999_cnv[],
    icudt57l_nfkc_nrm[],
    icudt57l_nfkc_cf_nrm[],
    icudt57l_uts46_nrm[];

U_EXPORT struct {
    uint16_t headerSize;
    uint8_t magic1, magic2;
    UDataInfo info;
    char padding[8];
    uint32_t count, reserved;
    struct {
        const char *name;
        const void *data;
    } toc[8];
} U_EXPORT2 icudt57_dat = {
    32, 0xda, 0x27, {
        20, 0,
        0, 0, 2, 0,
        {0x54, 0x6f, 0x43, 0x50},
        {1, 0, 0, 0},
        {0, 0, 0, 0}
    },
    "", 8, 0, {
        { "icudt57l/cnvalias.icu", icudt57l_cnvalias_icu },
        { "icudt57l/confusables.cfu", icudt57l_confusables_cfu },
        { "icudt57l/ibm-943_P15A-2003.cnv", icudt57l_ibm_943_P15A_2003_cnv },
        { "icudt57l/ibm-949_P110-1999.cnv", icudt57l_ibm_949_P110_1999_cnv },
        { "icudt57l/ibm-949_P11A-1999.cnv", icudt57l_ibm_949_P11A_1999_cnv },
        { "icudt57l/nfkc.nrm", icudt57l_nfkc_nrm },
        { "icudt57l/nfkc_cf.nrm", icudt57l_nfkc_cf_nrm },
        { "icudt57l/uts46.nrm", icudt57l_uts46_nrm }
    }
};
