# AppVeyor CI Build.
# HOME path: ~
# Git clone path: c:\Project\tbag
# Reference: https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\Project\tbag

# environment variables
environment:
  TBAG_HOME: c:\Project\tbag
  TBAG_BUILD: c:\Project\tbag\build

# build cache to preserve files/folders between builds
cache:
  - %TBAG_BUILD%\external\local

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# scripts to run before build
before_build:
  - cmd: echo Running before build...
  - cmd: mkdir "%TBAG_BUILD%"
  - cmd: cd "%TBAG_BUILD%"
  - cmd: if "%platform%" == "Win32" cmake -G "Visual Studio 14 2015"       -DCMAKE_BUILD_TYPE=Debug "%TBAG_HOME%"
  - cmd: if "%platform%" == "x64"   cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Debug "%TBAG_HOME%"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: echo Running build...
  - cmd: cd "%TBAG_BUILD%"
  - cmd: msbuild tea-bag.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - cmd: echo Running test...
  - cmd: cd "%TBAG_BUILD%\\Debug"
  - cmd: tester.exe

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - osom8979@gmail.com

