# AppVeyor CI Build.
# HOME path: ~
# Git clone path: c:\Project\tbag

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\Project\tbag

# environment variables
environment:
  TBAG_HOME: c:\Project\tbag
  TBAG_BUILD: c:\Project\tbag-build

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true            # enable MSBuild parallel builds
  project: tea-bag.sln      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - mkdir c:\Project\tbag-build
  - cd "%TBAG_BUILD%"
  - cmake -G "Visual Studio 15 2017 Win64" "%TBAG_BUILD%"

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
before_test:
  - echo script1
  - ps: Write-Host "script1"

# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - echo Running test...
  - "%TBAG_BUILD%\\tester.exe"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:

# on build failure
on_failure:

# after build failure or success
on_finish:

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - osom8979@gmail.com

