# Travis CI Build.
# HOME path: /home/travis
# Git clone path: /home/travis/build/osom8979/tbag

language: cpp

cache:
    apt: true

compiler: gcc

before_install:
    - export THREAD_NUM=4
    - export TPARTY_HOME=$HOME/tparty
    - export LD_LIBRARY_PATH=$TPARTY_HOME/local/lib:$LD_LIBRARY_PATH
    - sudo apt-get -qq update
    - sudo apt-get install -y git cmake

install:
    - echo $PWD
    - pushd .
    - git clone https://github.com/osom8979/tparty.git $TPARTY_HOME
    - cd $TPARTY_HOME
    - echo 'tinyxml2.sh' >> cache
    - echo 'spdlog.sh'   >> cache
    - echo 'ncurses.sh'  >> cache
    - ./install.sh -y
    - popd

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$THREAD_NUM
    - ./tester

notifications:
    email:
        on_success: always
        on_failure: always

