#ifndef NNG_TRANSPORT_WS_WEBSOCKET_H
#define NNG_TRANSPORT_WS_WEBSOCKET_H

#define NNG_OPT_WS_REQUEST_HEADERS "ws:request-headers"
#define NNG_OPT_WS_RESPONSE_HEADERS "ws:response-headers"
#define NNG_OPT_WSS_REQUEST_HEADERS NNG_OPT_WS_REQUEST_HEADERS
#define NNG_OPT_WSS_RESPONSE_HEADERS NNG_OPT_WS_RESPONSE_HEADERS

#endif // NNG_TRANSPORT_WS_WEBSOCKET_H
