/**
 * @file   Repeat.hpp
 * @brief  Repeat preprocessor prototype.
 * @author zer0
 * @date   2017-09-14
 */

#ifndef __INCLUDE_LIBTBAG__LIBTBAG_PREPROCESSOR_DETAILS_REPEAT_HPP__
#define __INCLUDE_LIBTBAG__LIBTBAG_PREPROCESSOR_DETAILS_REPEAT_HPP__

// MS compatible compilers support #pragma once
#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#ifndef TBAG_PP_REPEAT
# /* Macro Syntax: macro(size, number, data) */
#define TBAG_PP_REPEAT(count, macro, data) TBAG_PP_REPEAT_IMPL(count, macro, data)
#endif

#ifndef TBAG_PP_REPEAT_IMPL
#define TBAG_PP_REPEAT_IMPL(count, macro, data) TBAG_PP_REPEAT_##count(count, macro, data)
#endif

#define TBAG_PP_REPEAT_0(s, m, d)
#define TBAG_PP_REPEAT_1(s, m, d) TBAG_PP_REPEAT_0(s, m, d) m(s, 0, d)
#define TBAG_PP_REPEAT_2(s, m, d) TBAG_PP_REPEAT_1(s, m, d) m(s, 1, d)
#define TBAG_PP_REPEAT_3(s, m, d) TBAG_PP_REPEAT_2(s, m, d) m(s, 2, d)
#define TBAG_PP_REPEAT_4(s, m, d) TBAG_PP_REPEAT_3(s, m, d) m(s, 3, d)
#define TBAG_PP_REPEAT_5(s, m, d) TBAG_PP_REPEAT_4(s, m, d) m(s, 4, d)
#define TBAG_PP_REPEAT_6(s, m, d) TBAG_PP_REPEAT_5(s, m, d) m(s, 5, d)
#define TBAG_PP_REPEAT_7(s, m, d) TBAG_PP_REPEAT_6(s, m, d) m(s, 6, d)
#define TBAG_PP_REPEAT_8(s, m, d) TBAG_PP_REPEAT_7(s, m, d) m(s, 7, d)
#define TBAG_PP_REPEAT_9(s, m, d) TBAG_PP_REPEAT_8(s, m, d) m(s, 8, d)
#define TBAG_PP_REPEAT_10(s, m, d) TBAG_PP_REPEAT_9(s, m, d) m(s, 9, d)
#define TBAG_PP_REPEAT_11(s, m, d) TBAG_PP_REPEAT_10(s, m, d) m(s, 10, d)
#define TBAG_PP_REPEAT_12(s, m, d) TBAG_PP_REPEAT_11(s, m, d) m(s, 11, d)
#define TBAG_PP_REPEAT_13(s, m, d) TBAG_PP_REPEAT_12(s, m, d) m(s, 12, d)
#define TBAG_PP_REPEAT_14(s, m, d) TBAG_PP_REPEAT_13(s, m, d) m(s, 13, d)
#define TBAG_PP_REPEAT_15(s, m, d) TBAG_PP_REPEAT_14(s, m, d) m(s, 14, d)
#define TBAG_PP_REPEAT_16(s, m, d) TBAG_PP_REPEAT_15(s, m, d) m(s, 15, d)
#define TBAG_PP_REPEAT_17(s, m, d) TBAG_PP_REPEAT_16(s, m, d) m(s, 16, d)
#define TBAG_PP_REPEAT_18(s, m, d) TBAG_PP_REPEAT_17(s, m, d) m(s, 17, d)
#define TBAG_PP_REPEAT_19(s, m, d) TBAG_PP_REPEAT_18(s, m, d) m(s, 18, d)
#define TBAG_PP_REPEAT_20(s, m, d) TBAG_PP_REPEAT_19(s, m, d) m(s, 19, d)
#define TBAG_PP_REPEAT_21(s, m, d) TBAG_PP_REPEAT_20(s, m, d) m(s, 20, d)
#define TBAG_PP_REPEAT_22(s, m, d) TBAG_PP_REPEAT_21(s, m, d) m(s, 21, d)
#define TBAG_PP_REPEAT_23(s, m, d) TBAG_PP_REPEAT_22(s, m, d) m(s, 22, d)
#define TBAG_PP_REPEAT_24(s, m, d) TBAG_PP_REPEAT_23(s, m, d) m(s, 23, d)
#define TBAG_PP_REPEAT_25(s, m, d) TBAG_PP_REPEAT_24(s, m, d) m(s, 24, d)
#define TBAG_PP_REPEAT_26(s, m, d) TBAG_PP_REPEAT_25(s, m, d) m(s, 25, d)
#define TBAG_PP_REPEAT_27(s, m, d) TBAG_PP_REPEAT_26(s, m, d) m(s, 26, d)
#define TBAG_PP_REPEAT_28(s, m, d) TBAG_PP_REPEAT_27(s, m, d) m(s, 27, d)
#define TBAG_PP_REPEAT_29(s, m, d) TBAG_PP_REPEAT_28(s, m, d) m(s, 28, d)
#define TBAG_PP_REPEAT_30(s, m, d) TBAG_PP_REPEAT_29(s, m, d) m(s, 29, d)
#define TBAG_PP_REPEAT_31(s, m, d) TBAG_PP_REPEAT_30(s, m, d) m(s, 30, d)
#define TBAG_PP_REPEAT_32(s, m, d) TBAG_PP_REPEAT_31(s, m, d) m(s, 31, d)
#define TBAG_PP_REPEAT_33(s, m, d) TBAG_PP_REPEAT_32(s, m, d) m(s, 32, d)
#define TBAG_PP_REPEAT_34(s, m, d) TBAG_PP_REPEAT_33(s, m, d) m(s, 33, d)
#define TBAG_PP_REPEAT_35(s, m, d) TBAG_PP_REPEAT_34(s, m, d) m(s, 34, d)
#define TBAG_PP_REPEAT_36(s, m, d) TBAG_PP_REPEAT_35(s, m, d) m(s, 35, d)
#define TBAG_PP_REPEAT_37(s, m, d) TBAG_PP_REPEAT_36(s, m, d) m(s, 36, d)
#define TBAG_PP_REPEAT_38(s, m, d) TBAG_PP_REPEAT_37(s, m, d) m(s, 37, d)
#define TBAG_PP_REPEAT_39(s, m, d) TBAG_PP_REPEAT_38(s, m, d) m(s, 38, d)
#define TBAG_PP_REPEAT_40(s, m, d) TBAG_PP_REPEAT_39(s, m, d) m(s, 39, d)
#define TBAG_PP_REPEAT_41(s, m, d) TBAG_PP_REPEAT_40(s, m, d) m(s, 40, d)
#define TBAG_PP_REPEAT_42(s, m, d) TBAG_PP_REPEAT_41(s, m, d) m(s, 41, d)
#define TBAG_PP_REPEAT_43(s, m, d) TBAG_PP_REPEAT_42(s, m, d) m(s, 42, d)
#define TBAG_PP_REPEAT_44(s, m, d) TBAG_PP_REPEAT_43(s, m, d) m(s, 43, d)
#define TBAG_PP_REPEAT_45(s, m, d) TBAG_PP_REPEAT_44(s, m, d) m(s, 44, d)
#define TBAG_PP_REPEAT_46(s, m, d) TBAG_PP_REPEAT_45(s, m, d) m(s, 45, d)
#define TBAG_PP_REPEAT_47(s, m, d) TBAG_PP_REPEAT_46(s, m, d) m(s, 46, d)
#define TBAG_PP_REPEAT_48(s, m, d) TBAG_PP_REPEAT_47(s, m, d) m(s, 47, d)
#define TBAG_PP_REPEAT_49(s, m, d) TBAG_PP_REPEAT_48(s, m, d) m(s, 48, d)
#define TBAG_PP_REPEAT_50(s, m, d) TBAG_PP_REPEAT_49(s, m, d) m(s, 49, d)
#define TBAG_PP_REPEAT_51(s, m, d) TBAG_PP_REPEAT_50(s, m, d) m(s, 50, d)
#define TBAG_PP_REPEAT_52(s, m, d) TBAG_PP_REPEAT_51(s, m, d) m(s, 51, d)
#define TBAG_PP_REPEAT_53(s, m, d) TBAG_PP_REPEAT_52(s, m, d) m(s, 52, d)
#define TBAG_PP_REPEAT_54(s, m, d) TBAG_PP_REPEAT_53(s, m, d) m(s, 53, d)
#define TBAG_PP_REPEAT_55(s, m, d) TBAG_PP_REPEAT_54(s, m, d) m(s, 54, d)
#define TBAG_PP_REPEAT_56(s, m, d) TBAG_PP_REPEAT_55(s, m, d) m(s, 55, d)
#define TBAG_PP_REPEAT_57(s, m, d) TBAG_PP_REPEAT_56(s, m, d) m(s, 56, d)
#define TBAG_PP_REPEAT_58(s, m, d) TBAG_PP_REPEAT_57(s, m, d) m(s, 57, d)
#define TBAG_PP_REPEAT_59(s, m, d) TBAG_PP_REPEAT_58(s, m, d) m(s, 58, d)
#define TBAG_PP_REPEAT_60(s, m, d) TBAG_PP_REPEAT_59(s, m, d) m(s, 59, d)
#define TBAG_PP_REPEAT_61(s, m, d) TBAG_PP_REPEAT_60(s, m, d) m(s, 60, d)
#define TBAG_PP_REPEAT_62(s, m, d) TBAG_PP_REPEAT_61(s, m, d) m(s, 61, d)
#define TBAG_PP_REPEAT_63(s, m, d) TBAG_PP_REPEAT_62(s, m, d) m(s, 62, d)
#define TBAG_PP_REPEAT_64(s, m, d) TBAG_PP_REPEAT_63(s, m, d) m(s, 63, d)
#define TBAG_PP_REPEAT_65(s, m, d) TBAG_PP_REPEAT_64(s, m, d) m(s, 64, d)
#define TBAG_PP_REPEAT_66(s, m, d) TBAG_PP_REPEAT_65(s, m, d) m(s, 65, d)
#define TBAG_PP_REPEAT_67(s, m, d) TBAG_PP_REPEAT_66(s, m, d) m(s, 66, d)
#define TBAG_PP_REPEAT_68(s, m, d) TBAG_PP_REPEAT_67(s, m, d) m(s, 67, d)
#define TBAG_PP_REPEAT_69(s, m, d) TBAG_PP_REPEAT_68(s, m, d) m(s, 68, d)
#define TBAG_PP_REPEAT_70(s, m, d) TBAG_PP_REPEAT_69(s, m, d) m(s, 69, d)
#define TBAG_PP_REPEAT_71(s, m, d) TBAG_PP_REPEAT_70(s, m, d) m(s, 70, d)
#define TBAG_PP_REPEAT_72(s, m, d) TBAG_PP_REPEAT_71(s, m, d) m(s, 71, d)
#define TBAG_PP_REPEAT_73(s, m, d) TBAG_PP_REPEAT_72(s, m, d) m(s, 72, d)
#define TBAG_PP_REPEAT_74(s, m, d) TBAG_PP_REPEAT_73(s, m, d) m(s, 73, d)
#define TBAG_PP_REPEAT_75(s, m, d) TBAG_PP_REPEAT_74(s, m, d) m(s, 74, d)
#define TBAG_PP_REPEAT_76(s, m, d) TBAG_PP_REPEAT_75(s, m, d) m(s, 75, d)
#define TBAG_PP_REPEAT_77(s, m, d) TBAG_PP_REPEAT_76(s, m, d) m(s, 76, d)
#define TBAG_PP_REPEAT_78(s, m, d) TBAG_PP_REPEAT_77(s, m, d) m(s, 77, d)
#define TBAG_PP_REPEAT_79(s, m, d) TBAG_PP_REPEAT_78(s, m, d) m(s, 78, d)
#define TBAG_PP_REPEAT_80(s, m, d) TBAG_PP_REPEAT_79(s, m, d) m(s, 79, d)
#define TBAG_PP_REPEAT_81(s, m, d) TBAG_PP_REPEAT_80(s, m, d) m(s, 80, d)
#define TBAG_PP_REPEAT_82(s, m, d) TBAG_PP_REPEAT_81(s, m, d) m(s, 81, d)
#define TBAG_PP_REPEAT_83(s, m, d) TBAG_PP_REPEAT_82(s, m, d) m(s, 82, d)
#define TBAG_PP_REPEAT_84(s, m, d) TBAG_PP_REPEAT_83(s, m, d) m(s, 83, d)
#define TBAG_PP_REPEAT_85(s, m, d) TBAG_PP_REPEAT_84(s, m, d) m(s, 84, d)
#define TBAG_PP_REPEAT_86(s, m, d) TBAG_PP_REPEAT_85(s, m, d) m(s, 85, d)
#define TBAG_PP_REPEAT_87(s, m, d) TBAG_PP_REPEAT_86(s, m, d) m(s, 86, d)
#define TBAG_PP_REPEAT_88(s, m, d) TBAG_PP_REPEAT_87(s, m, d) m(s, 87, d)
#define TBAG_PP_REPEAT_89(s, m, d) TBAG_PP_REPEAT_88(s, m, d) m(s, 88, d)
#define TBAG_PP_REPEAT_90(s, m, d) TBAG_PP_REPEAT_89(s, m, d) m(s, 89, d)
#define TBAG_PP_REPEAT_91(s, m, d) TBAG_PP_REPEAT_90(s, m, d) m(s, 90, d)
#define TBAG_PP_REPEAT_92(s, m, d) TBAG_PP_REPEAT_91(s, m, d) m(s, 91, d)
#define TBAG_PP_REPEAT_93(s, m, d) TBAG_PP_REPEAT_92(s, m, d) m(s, 92, d)
#define TBAG_PP_REPEAT_94(s, m, d) TBAG_PP_REPEAT_93(s, m, d) m(s, 93, d)
#define TBAG_PP_REPEAT_95(s, m, d) TBAG_PP_REPEAT_94(s, m, d) m(s, 94, d)
#define TBAG_PP_REPEAT_96(s, m, d) TBAG_PP_REPEAT_95(s, m, d) m(s, 95, d)
#define TBAG_PP_REPEAT_97(s, m, d) TBAG_PP_REPEAT_96(s, m, d) m(s, 96, d)
#define TBAG_PP_REPEAT_98(s, m, d) TBAG_PP_REPEAT_97(s, m, d) m(s, 97, d)
#define TBAG_PP_REPEAT_99(s, m, d) TBAG_PP_REPEAT_98(s, m, d) m(s, 98, d)
#define TBAG_PP_REPEAT_100(s, m, d) TBAG_PP_REPEAT_99(s, m, d) m(s, 99, d)
#define TBAG_PP_REPEAT_101(s, m, d) TBAG_PP_REPEAT_100(s, m, d) m(s, 100, d)
#define TBAG_PP_REPEAT_102(s, m, d) TBAG_PP_REPEAT_101(s, m, d) m(s, 101, d)
#define TBAG_PP_REPEAT_103(s, m, d) TBAG_PP_REPEAT_102(s, m, d) m(s, 102, d)
#define TBAG_PP_REPEAT_104(s, m, d) TBAG_PP_REPEAT_103(s, m, d) m(s, 103, d)
#define TBAG_PP_REPEAT_105(s, m, d) TBAG_PP_REPEAT_104(s, m, d) m(s, 104, d)
#define TBAG_PP_REPEAT_106(s, m, d) TBAG_PP_REPEAT_105(s, m, d) m(s, 105, d)
#define TBAG_PP_REPEAT_107(s, m, d) TBAG_PP_REPEAT_106(s, m, d) m(s, 106, d)
#define TBAG_PP_REPEAT_108(s, m, d) TBAG_PP_REPEAT_107(s, m, d) m(s, 107, d)
#define TBAG_PP_REPEAT_109(s, m, d) TBAG_PP_REPEAT_108(s, m, d) m(s, 108, d)
#define TBAG_PP_REPEAT_110(s, m, d) TBAG_PP_REPEAT_109(s, m, d) m(s, 109, d)
#define TBAG_PP_REPEAT_111(s, m, d) TBAG_PP_REPEAT_110(s, m, d) m(s, 110, d)
#define TBAG_PP_REPEAT_112(s, m, d) TBAG_PP_REPEAT_111(s, m, d) m(s, 111, d)
#define TBAG_PP_REPEAT_113(s, m, d) TBAG_PP_REPEAT_112(s, m, d) m(s, 112, d)
#define TBAG_PP_REPEAT_114(s, m, d) TBAG_PP_REPEAT_113(s, m, d) m(s, 113, d)
#define TBAG_PP_REPEAT_115(s, m, d) TBAG_PP_REPEAT_114(s, m, d) m(s, 114, d)
#define TBAG_PP_REPEAT_116(s, m, d) TBAG_PP_REPEAT_115(s, m, d) m(s, 115, d)
#define TBAG_PP_REPEAT_117(s, m, d) TBAG_PP_REPEAT_116(s, m, d) m(s, 116, d)
#define TBAG_PP_REPEAT_118(s, m, d) TBAG_PP_REPEAT_117(s, m, d) m(s, 117, d)
#define TBAG_PP_REPEAT_119(s, m, d) TBAG_PP_REPEAT_118(s, m, d) m(s, 118, d)
#define TBAG_PP_REPEAT_120(s, m, d) TBAG_PP_REPEAT_119(s, m, d) m(s, 119, d)
#define TBAG_PP_REPEAT_121(s, m, d) TBAG_PP_REPEAT_120(s, m, d) m(s, 120, d)
#define TBAG_PP_REPEAT_122(s, m, d) TBAG_PP_REPEAT_121(s, m, d) m(s, 121, d)
#define TBAG_PP_REPEAT_123(s, m, d) TBAG_PP_REPEAT_122(s, m, d) m(s, 122, d)
#define TBAG_PP_REPEAT_124(s, m, d) TBAG_PP_REPEAT_123(s, m, d) m(s, 123, d)
#define TBAG_PP_REPEAT_125(s, m, d) TBAG_PP_REPEAT_124(s, m, d) m(s, 124, d)
#define TBAG_PP_REPEAT_126(s, m, d) TBAG_PP_REPEAT_125(s, m, d) m(s, 125, d)
#define TBAG_PP_REPEAT_127(s, m, d) TBAG_PP_REPEAT_126(s, m, d) m(s, 126, d)
#define TBAG_PP_REPEAT_128(s, m, d) TBAG_PP_REPEAT_127(s, m, d) m(s, 127, d)
#define TBAG_PP_REPEAT_129(s, m, d) TBAG_PP_REPEAT_128(s, m, d) m(s, 128, d)
#define TBAG_PP_REPEAT_130(s, m, d) TBAG_PP_REPEAT_129(s, m, d) m(s, 129, d)
#define TBAG_PP_REPEAT_131(s, m, d) TBAG_PP_REPEAT_130(s, m, d) m(s, 130, d)
#define TBAG_PP_REPEAT_132(s, m, d) TBAG_PP_REPEAT_131(s, m, d) m(s, 131, d)
#define TBAG_PP_REPEAT_133(s, m, d) TBAG_PP_REPEAT_132(s, m, d) m(s, 132, d)
#define TBAG_PP_REPEAT_134(s, m, d) TBAG_PP_REPEAT_133(s, m, d) m(s, 133, d)
#define TBAG_PP_REPEAT_135(s, m, d) TBAG_PP_REPEAT_134(s, m, d) m(s, 134, d)
#define TBAG_PP_REPEAT_136(s, m, d) TBAG_PP_REPEAT_135(s, m, d) m(s, 135, d)
#define TBAG_PP_REPEAT_137(s, m, d) TBAG_PP_REPEAT_136(s, m, d) m(s, 136, d)
#define TBAG_PP_REPEAT_138(s, m, d) TBAG_PP_REPEAT_137(s, m, d) m(s, 137, d)
#define TBAG_PP_REPEAT_139(s, m, d) TBAG_PP_REPEAT_138(s, m, d) m(s, 138, d)
#define TBAG_PP_REPEAT_140(s, m, d) TBAG_PP_REPEAT_139(s, m, d) m(s, 139, d)
#define TBAG_PP_REPEAT_141(s, m, d) TBAG_PP_REPEAT_140(s, m, d) m(s, 140, d)
#define TBAG_PP_REPEAT_142(s, m, d) TBAG_PP_REPEAT_141(s, m, d) m(s, 141, d)
#define TBAG_PP_REPEAT_143(s, m, d) TBAG_PP_REPEAT_142(s, m, d) m(s, 142, d)
#define TBAG_PP_REPEAT_144(s, m, d) TBAG_PP_REPEAT_143(s, m, d) m(s, 143, d)
#define TBAG_PP_REPEAT_145(s, m, d) TBAG_PP_REPEAT_144(s, m, d) m(s, 144, d)
#define TBAG_PP_REPEAT_146(s, m, d) TBAG_PP_REPEAT_145(s, m, d) m(s, 145, d)
#define TBAG_PP_REPEAT_147(s, m, d) TBAG_PP_REPEAT_146(s, m, d) m(s, 146, d)
#define TBAG_PP_REPEAT_148(s, m, d) TBAG_PP_REPEAT_147(s, m, d) m(s, 147, d)
#define TBAG_PP_REPEAT_149(s, m, d) TBAG_PP_REPEAT_148(s, m, d) m(s, 148, d)
#define TBAG_PP_REPEAT_150(s, m, d) TBAG_PP_REPEAT_149(s, m, d) m(s, 149, d)
#define TBAG_PP_REPEAT_151(s, m, d) TBAG_PP_REPEAT_150(s, m, d) m(s, 150, d)
#define TBAG_PP_REPEAT_152(s, m, d) TBAG_PP_REPEAT_151(s, m, d) m(s, 151, d)
#define TBAG_PP_REPEAT_153(s, m, d) TBAG_PP_REPEAT_152(s, m, d) m(s, 152, d)
#define TBAG_PP_REPEAT_154(s, m, d) TBAG_PP_REPEAT_153(s, m, d) m(s, 153, d)
#define TBAG_PP_REPEAT_155(s, m, d) TBAG_PP_REPEAT_154(s, m, d) m(s, 154, d)
#define TBAG_PP_REPEAT_156(s, m, d) TBAG_PP_REPEAT_155(s, m, d) m(s, 155, d)
#define TBAG_PP_REPEAT_157(s, m, d) TBAG_PP_REPEAT_156(s, m, d) m(s, 156, d)
#define TBAG_PP_REPEAT_158(s, m, d) TBAG_PP_REPEAT_157(s, m, d) m(s, 157, d)
#define TBAG_PP_REPEAT_159(s, m, d) TBAG_PP_REPEAT_158(s, m, d) m(s, 158, d)
#define TBAG_PP_REPEAT_160(s, m, d) TBAG_PP_REPEAT_159(s, m, d) m(s, 159, d)
#define TBAG_PP_REPEAT_161(s, m, d) TBAG_PP_REPEAT_160(s, m, d) m(s, 160, d)
#define TBAG_PP_REPEAT_162(s, m, d) TBAG_PP_REPEAT_161(s, m, d) m(s, 161, d)
#define TBAG_PP_REPEAT_163(s, m, d) TBAG_PP_REPEAT_162(s, m, d) m(s, 162, d)
#define TBAG_PP_REPEAT_164(s, m, d) TBAG_PP_REPEAT_163(s, m, d) m(s, 163, d)
#define TBAG_PP_REPEAT_165(s, m, d) TBAG_PP_REPEAT_164(s, m, d) m(s, 164, d)
#define TBAG_PP_REPEAT_166(s, m, d) TBAG_PP_REPEAT_165(s, m, d) m(s, 165, d)
#define TBAG_PP_REPEAT_167(s, m, d) TBAG_PP_REPEAT_166(s, m, d) m(s, 166, d)
#define TBAG_PP_REPEAT_168(s, m, d) TBAG_PP_REPEAT_167(s, m, d) m(s, 167, d)
#define TBAG_PP_REPEAT_169(s, m, d) TBAG_PP_REPEAT_168(s, m, d) m(s, 168, d)
#define TBAG_PP_REPEAT_170(s, m, d) TBAG_PP_REPEAT_169(s, m, d) m(s, 169, d)
#define TBAG_PP_REPEAT_171(s, m, d) TBAG_PP_REPEAT_170(s, m, d) m(s, 170, d)
#define TBAG_PP_REPEAT_172(s, m, d) TBAG_PP_REPEAT_171(s, m, d) m(s, 171, d)
#define TBAG_PP_REPEAT_173(s, m, d) TBAG_PP_REPEAT_172(s, m, d) m(s, 172, d)
#define TBAG_PP_REPEAT_174(s, m, d) TBAG_PP_REPEAT_173(s, m, d) m(s, 173, d)
#define TBAG_PP_REPEAT_175(s, m, d) TBAG_PP_REPEAT_174(s, m, d) m(s, 174, d)
#define TBAG_PP_REPEAT_176(s, m, d) TBAG_PP_REPEAT_175(s, m, d) m(s, 175, d)
#define TBAG_PP_REPEAT_177(s, m, d) TBAG_PP_REPEAT_176(s, m, d) m(s, 176, d)
#define TBAG_PP_REPEAT_178(s, m, d) TBAG_PP_REPEAT_177(s, m, d) m(s, 177, d)
#define TBAG_PP_REPEAT_179(s, m, d) TBAG_PP_REPEAT_178(s, m, d) m(s, 178, d)
#define TBAG_PP_REPEAT_180(s, m, d) TBAG_PP_REPEAT_179(s, m, d) m(s, 179, d)
#define TBAG_PP_REPEAT_181(s, m, d) TBAG_PP_REPEAT_180(s, m, d) m(s, 180, d)
#define TBAG_PP_REPEAT_182(s, m, d) TBAG_PP_REPEAT_181(s, m, d) m(s, 181, d)
#define TBAG_PP_REPEAT_183(s, m, d) TBAG_PP_REPEAT_182(s, m, d) m(s, 182, d)
#define TBAG_PP_REPEAT_184(s, m, d) TBAG_PP_REPEAT_183(s, m, d) m(s, 183, d)
#define TBAG_PP_REPEAT_185(s, m, d) TBAG_PP_REPEAT_184(s, m, d) m(s, 184, d)
#define TBAG_PP_REPEAT_186(s, m, d) TBAG_PP_REPEAT_185(s, m, d) m(s, 185, d)
#define TBAG_PP_REPEAT_187(s, m, d) TBAG_PP_REPEAT_186(s, m, d) m(s, 186, d)
#define TBAG_PP_REPEAT_188(s, m, d) TBAG_PP_REPEAT_187(s, m, d) m(s, 187, d)
#define TBAG_PP_REPEAT_189(s, m, d) TBAG_PP_REPEAT_188(s, m, d) m(s, 188, d)
#define TBAG_PP_REPEAT_190(s, m, d) TBAG_PP_REPEAT_189(s, m, d) m(s, 189, d)
#define TBAG_PP_REPEAT_191(s, m, d) TBAG_PP_REPEAT_190(s, m, d) m(s, 190, d)
#define TBAG_PP_REPEAT_192(s, m, d) TBAG_PP_REPEAT_191(s, m, d) m(s, 191, d)
#define TBAG_PP_REPEAT_193(s, m, d) TBAG_PP_REPEAT_192(s, m, d) m(s, 192, d)
#define TBAG_PP_REPEAT_194(s, m, d) TBAG_PP_REPEAT_193(s, m, d) m(s, 193, d)
#define TBAG_PP_REPEAT_195(s, m, d) TBAG_PP_REPEAT_194(s, m, d) m(s, 194, d)
#define TBAG_PP_REPEAT_196(s, m, d) TBAG_PP_REPEAT_195(s, m, d) m(s, 195, d)
#define TBAG_PP_REPEAT_197(s, m, d) TBAG_PP_REPEAT_196(s, m, d) m(s, 196, d)
#define TBAG_PP_REPEAT_198(s, m, d) TBAG_PP_REPEAT_197(s, m, d) m(s, 197, d)
#define TBAG_PP_REPEAT_199(s, m, d) TBAG_PP_REPEAT_198(s, m, d) m(s, 198, d)
#define TBAG_PP_REPEAT_200(s, m, d) TBAG_PP_REPEAT_199(s, m, d) m(s, 199, d)
#define TBAG_PP_REPEAT_201(s, m, d) TBAG_PP_REPEAT_200(s, m, d) m(s, 200, d)
#define TBAG_PP_REPEAT_202(s, m, d) TBAG_PP_REPEAT_201(s, m, d) m(s, 201, d)
#define TBAG_PP_REPEAT_203(s, m, d) TBAG_PP_REPEAT_202(s, m, d) m(s, 202, d)
#define TBAG_PP_REPEAT_204(s, m, d) TBAG_PP_REPEAT_203(s, m, d) m(s, 203, d)
#define TBAG_PP_REPEAT_205(s, m, d) TBAG_PP_REPEAT_204(s, m, d) m(s, 204, d)
#define TBAG_PP_REPEAT_206(s, m, d) TBAG_PP_REPEAT_205(s, m, d) m(s, 205, d)
#define TBAG_PP_REPEAT_207(s, m, d) TBAG_PP_REPEAT_206(s, m, d) m(s, 206, d)
#define TBAG_PP_REPEAT_208(s, m, d) TBAG_PP_REPEAT_207(s, m, d) m(s, 207, d)
#define TBAG_PP_REPEAT_209(s, m, d) TBAG_PP_REPEAT_208(s, m, d) m(s, 208, d)
#define TBAG_PP_REPEAT_210(s, m, d) TBAG_PP_REPEAT_209(s, m, d) m(s, 209, d)
#define TBAG_PP_REPEAT_211(s, m, d) TBAG_PP_REPEAT_210(s, m, d) m(s, 210, d)
#define TBAG_PP_REPEAT_212(s, m, d) TBAG_PP_REPEAT_211(s, m, d) m(s, 211, d)
#define TBAG_PP_REPEAT_213(s, m, d) TBAG_PP_REPEAT_212(s, m, d) m(s, 212, d)
#define TBAG_PP_REPEAT_214(s, m, d) TBAG_PP_REPEAT_213(s, m, d) m(s, 213, d)
#define TBAG_PP_REPEAT_215(s, m, d) TBAG_PP_REPEAT_214(s, m, d) m(s, 214, d)
#define TBAG_PP_REPEAT_216(s, m, d) TBAG_PP_REPEAT_215(s, m, d) m(s, 215, d)
#define TBAG_PP_REPEAT_217(s, m, d) TBAG_PP_REPEAT_216(s, m, d) m(s, 216, d)
#define TBAG_PP_REPEAT_218(s, m, d) TBAG_PP_REPEAT_217(s, m, d) m(s, 217, d)
#define TBAG_PP_REPEAT_219(s, m, d) TBAG_PP_REPEAT_218(s, m, d) m(s, 218, d)
#define TBAG_PP_REPEAT_220(s, m, d) TBAG_PP_REPEAT_219(s, m, d) m(s, 219, d)
#define TBAG_PP_REPEAT_221(s, m, d) TBAG_PP_REPEAT_220(s, m, d) m(s, 220, d)
#define TBAG_PP_REPEAT_222(s, m, d) TBAG_PP_REPEAT_221(s, m, d) m(s, 221, d)
#define TBAG_PP_REPEAT_223(s, m, d) TBAG_PP_REPEAT_222(s, m, d) m(s, 222, d)
#define TBAG_PP_REPEAT_224(s, m, d) TBAG_PP_REPEAT_223(s, m, d) m(s, 223, d)
#define TBAG_PP_REPEAT_225(s, m, d) TBAG_PP_REPEAT_224(s, m, d) m(s, 224, d)
#define TBAG_PP_REPEAT_226(s, m, d) TBAG_PP_REPEAT_225(s, m, d) m(s, 225, d)
#define TBAG_PP_REPEAT_227(s, m, d) TBAG_PP_REPEAT_226(s, m, d) m(s, 226, d)
#define TBAG_PP_REPEAT_228(s, m, d) TBAG_PP_REPEAT_227(s, m, d) m(s, 227, d)
#define TBAG_PP_REPEAT_229(s, m, d) TBAG_PP_REPEAT_228(s, m, d) m(s, 228, d)
#define TBAG_PP_REPEAT_230(s, m, d) TBAG_PP_REPEAT_229(s, m, d) m(s, 229, d)
#define TBAG_PP_REPEAT_231(s, m, d) TBAG_PP_REPEAT_230(s, m, d) m(s, 230, d)
#define TBAG_PP_REPEAT_232(s, m, d) TBAG_PP_REPEAT_231(s, m, d) m(s, 231, d)
#define TBAG_PP_REPEAT_233(s, m, d) TBAG_PP_REPEAT_232(s, m, d) m(s, 232, d)
#define TBAG_PP_REPEAT_234(s, m, d) TBAG_PP_REPEAT_233(s, m, d) m(s, 233, d)
#define TBAG_PP_REPEAT_235(s, m, d) TBAG_PP_REPEAT_234(s, m, d) m(s, 234, d)
#define TBAG_PP_REPEAT_236(s, m, d) TBAG_PP_REPEAT_235(s, m, d) m(s, 235, d)
#define TBAG_PP_REPEAT_237(s, m, d) TBAG_PP_REPEAT_236(s, m, d) m(s, 236, d)
#define TBAG_PP_REPEAT_238(s, m, d) TBAG_PP_REPEAT_237(s, m, d) m(s, 237, d)
#define TBAG_PP_REPEAT_239(s, m, d) TBAG_PP_REPEAT_238(s, m, d) m(s, 238, d)
#define TBAG_PP_REPEAT_240(s, m, d) TBAG_PP_REPEAT_239(s, m, d) m(s, 239, d)
#define TBAG_PP_REPEAT_241(s, m, d) TBAG_PP_REPEAT_240(s, m, d) m(s, 240, d)
#define TBAG_PP_REPEAT_242(s, m, d) TBAG_PP_REPEAT_241(s, m, d) m(s, 241, d)
#define TBAG_PP_REPEAT_243(s, m, d) TBAG_PP_REPEAT_242(s, m, d) m(s, 242, d)
#define TBAG_PP_REPEAT_244(s, m, d) TBAG_PP_REPEAT_243(s, m, d) m(s, 243, d)
#define TBAG_PP_REPEAT_245(s, m, d) TBAG_PP_REPEAT_244(s, m, d) m(s, 244, d)
#define TBAG_PP_REPEAT_246(s, m, d) TBAG_PP_REPEAT_245(s, m, d) m(s, 245, d)
#define TBAG_PP_REPEAT_247(s, m, d) TBAG_PP_REPEAT_246(s, m, d) m(s, 246, d)
#define TBAG_PP_REPEAT_248(s, m, d) TBAG_PP_REPEAT_247(s, m, d) m(s, 247, d)
#define TBAG_PP_REPEAT_249(s, m, d) TBAG_PP_REPEAT_248(s, m, d) m(s, 248, d)
#define TBAG_PP_REPEAT_250(s, m, d) TBAG_PP_REPEAT_249(s, m, d) m(s, 249, d)
#define TBAG_PP_REPEAT_251(s, m, d) TBAG_PP_REPEAT_250(s, m, d) m(s, 250, d)
#define TBAG_PP_REPEAT_252(s, m, d) TBAG_PP_REPEAT_251(s, m, d) m(s, 251, d)
#define TBAG_PP_REPEAT_253(s, m, d) TBAG_PP_REPEAT_252(s, m, d) m(s, 252, d)
#define TBAG_PP_REPEAT_254(s, m, d) TBAG_PP_REPEAT_253(s, m, d) m(s, 253, d)
#define TBAG_PP_REPEAT_255(s, m, d) TBAG_PP_REPEAT_254(s, m, d) m(s, 254, d)
#define TBAG_PP_REPEAT_256(s, m, d) TBAG_PP_REPEAT_255(s, m, d) m(s, 255, d)

#endif // __INCLUDE_LIBTBAG__LIBTBAG_PREPROCESSOR_DETAILS_REPEAT_HPP__

