FROM ubuntu:18.04
MAINTAINER zer0 <osom8979@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# For the add-apt-repository
RUN apt-get -qq update
RUN apt-get install -y g++ cmake

ENV WORKING_DIR  /working
ENV BUILD_DIR    /build

RUN mkdir $WORKING_DIR
RUN mkdir $BUILD_DIR

# tbag update.
COPY . $WORKING_DIR
WORKDIR $BUILD_DIR

# tbag build.
RUN cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release $WORKING_DIR
RUN make
RUN make install

# tbag test.
WORKDIR /
CMD /usr/local/bin/tpot

