FROM ubuntu:18.04
MAINTAINER zer0 <osom8979@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --fix-missing \
    g++ cmake software-properties-common git curl ccache doxygen graphviz \
    ocl-icd-opencl-dev libglu1-mesa-dev libudev-dev xorg-dev libxcb-image0-dev

ENV WORKING_DIR /tbag/working
ENV BUILD_DIR   /tbag/build

RUN mkdir -p $WORKING_DIR && \
    mkdir -p $BUILD_DIR

COPY . $WORKING_DIR
WORKDIR $BUILD_DIR

RUN cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release $WORKING_DIR && \
    make install
WORKDIR /
RUN rm -rf $BUILD_DIR $WORKING_DIR

CMD /usr/local/bin/tpot

