FROM ubuntu:14.04
MAINTAINER zer0 <osom8979@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# For the add-apt-repository
RUN apt-get -qq update
RUN apt-get install -y software-properties-common

# Dependencies.
RUN add-apt-repository --yes ppa:ubuntu-toolchain-r/test
RUN add-apt-repository --yes ppa:george-edison55/cmake-3.x
RUN apt-get -qq update
RUN apt-get install -y build-essential autoconf automake libtool pkg-config texinfo
RUN apt-get install -y curl git cmake cmake-data curl unzip g++-5
RUN apt-get install -y libreadline6 libreadline6-dev

ENV TPARTY_HOME      /tparty
ENV LD_LIBRARY_PATH  $TPARTY_HOME/local/lib:$LD_LIBRARY_PATH
ENV CXX              g++-5

ENV WORKING_DIR  /working
ENV BUILD_DIR    /build

RUN mkdir $WORKING_DIR
RUN mkdir $BUILD_DIR

# tbag update.
COPY . $WORKING_DIR
WORKDIR $BUILD_DIR

# tparty library.
RUN /bin/bash $WORKING_DIR/script/travis_install.sh

# tbag build.
RUN cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release $WORKING_DIR
RUN make
RUN make install

# tbag test.
WORKDIR /
CMD /usr/local/bin/tpot

