FROM ubuntu:18.04
MAINTAINER zer0 <osom8979@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update
RUN apt-get install -y g++ cmake
RUN apt-get install -y software-properties-common git curl ccache doxygen graphviz

ENV WORKING_DIR /tbag/working
ENV BUILD_DIR   /tbag/build

RUN mkdir -p $WORKING_DIR
RUN mkdir -p $BUILD_DIR

# tbag update.
COPY . $WORKING_DIR
WORKDIR $BUILD_DIR

# tbag build.
RUN cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release $WORKING_DIR
RUN make install

# run tpot.
WORKDIR /
CMD /usr/local/bin/tpot

