## CMake subproject properties.

set (TBAG_PROJECT_DEFINITIONS  -DUSE_LIBTEST_EXPORT)
set (TBAG_PROJECT_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR})
set (TBAG_PROJECT_LDFLAGS      -L${CMAKE_CURRENT_LIST_DIR})

